name: 'Docker Build and Push to GAR'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: write

jobs:
  docker:
    name: 'Docker Build & Push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/198711600574/locations/global/workloadIdentityPools/githubactions-provider/providers/github
          service_account: github-worload-identity-federa@easework-projects.iam.gserviceaccount.com
          token_format: access_token
          export_environment_variables: true

      - name: Configure Docker for Artifact Registry
        run: |
          echo '{"credHelpers": {"us-central1-docker.pkg.dev": "gcloud"}}' > ~/.docker/config.json

      - name: Build Docker Image
        run: |
          cd ../..
          docker build -t us-central1-docker.pkg.dev/easework-projects/easeworkai-essentail/demand-forcasting-api:3.0 .

      - name: Push Docker Image
        run: |
          docker push us-central1-docker.pkg.dev/easework-projects/easeworkai-essentail/demand-forcasting-api:3.0
